spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:http://localhost:8888
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/fitnessrecomendation
#      database: recomendation
#
#server:
#  port: 8083
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#rabbitmq:
#  exchange:
#    name: fitness.exchange
#  queue:
#    name: activity.queue
#  routing:
#    key: activity.tracking
#  host: localhost
#  port: 5672
#  username: guest
#  password: guest
#
#gemini:
#  api:
#    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
#    key: AIzaSyAc-PEVvv7aPS77pJYfkkyis-kvPnWPyWg
