spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8888"
#  datasource:
#    url: jdbc:postgresql://localhost:5432/FitnessUserDb
#    username: postgres
#    password: admin@123
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#
#server:
#  port: 8081
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
